# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

__version__ = version = "0.1.dev357+g4e1041c.d20240223"  # type: str
__version_tuple__ = version_tuple = (0, 1, "dev357", "g4e1041c.d20240223")  # type: tuple[int | str, ...]
